### ISSUE TITLE
Link to my simple CLI tool based on your lib?

### ISSUE THREAD

**Issue by 3noch** [jfischoff/twitch#18]
I love this library, but I didn't want to write Haskell code every time I needed this. So I wrote a very simple CLI to wrap its most basic features. Perhaps you'd be interested in linking to it. If you have ideas for how to improve it, I'm all ears. I only spent an hour or so on it since your library makes it so easy.

https://github.com/grafted-in/twitch-cli

Thanks for the great lib!

**Comment by jfischoff** [comment]
Very cool, adding.

**Comment by jfischoff** [comment]
Should the twitch-cli functionality get added to twitch? I've added you added you to the project FWIW.

**Comment by 3noch** [comment]
Thank you!

I did think of offering to integrate it. I'd be fine with that but my hesitation is that there really are *many* ways to provide a CLI for `twitch`. Mine just chooses one very simple way, but I could easily see other directions as well. Perhaps it's be possible to combine these into one one large CLI. Let me know your thoughts.

**Comment by jfischoff** [comment]
Yeah I was thinking that as well. Ill make place holder issue when I get
back to design a more full featured CLI using yours as inspiration. We can
discuss a design if/when we feel inspired.

**Comment by 3noch** [comment]
Great idea. Believe it or not, I sort of think a good CLI like this could take off in the OSS arena. I haven't found a good solution for this which is why I wrote one for myself. It seems each build system relies on their own custom watching functionality. But there is nothing to fill in the gaps other than `inotifywait` which is not fun to work with.

**Comment by 3noch** [comment]
Another idea would be to parse `Makefiles` and turn them and define watchers for each rule.

**Comment by 3noch** [comment]
`Shake` already has a parser for that: https://hackage.haskell.org/package/shake-0.15.11/docs/Development-Shake-Util.html

**Comment by jfischoff** [comment]
Currently what we are doing with at work is watching a entire directory and calling Shake. By doing I  mean the code is, but no one is actually using it so I can't speak to how well it works in practice. 

There is also http://entrproject.org/ which is another direction.

**Comment by 3noch** [comment]
Great thoughts. I see you've addressed this and you've opened #20. Thanks for the shout-out.

**Comment by jfischoff** [comment]
@3noch  I updated my comment

**Comment by 3noch** [comment]
@jfischoff Interesting! What you describe seems to overlap heavily with Nix which I use for everything. (But even nix doesn't have a file watching component hence me writing a CLI!!)

**Comment by jfischoff** [comment]
Indeed. I think it does overlap a look with Nix. I think what I am thinking of could be just yet another frontend for Nix. 

One of the annoying things about Nix is the distinction between the low level building `Make` etc and the derivations. The derivations outputs are all cached, but you want that behavior for all of the intermediates (obj files etc).

**Comment by 3noch** [comment]
Yes that's true. Apparently [work is being done to fix that](https://twitter.com/GabrielG439/status/870347675895349248).

**Comment by 3noch** [comment]
@jfischoff Just wanted to let you know that I've spent some time cleaning up my CLI and adding some basic features. It's more-or-less where I want it now. It supports canceling existing commands when a new event comes in, and it supports running multiple pattern/command pairs at once like your library allows. However, in the process I've actually dropped the dependency on `twitch` itself! My API was so simple that I ended up just using `fsnotify` and `Glob` directly. I hope the fact that my tool is called `twitch-cli` does not bother you since I'm no longer actually using `twitch`. However, the CLI API is still inspired by your library, so maybe that's enough?

One thing I learned is that for very deep and large folders, it's not enough to have only *one* root directory. Having one root means that `fsnotify` must watch the *entire* tree which ends up being way too slow. What I did was use `Glob`'s `commonDirectory` function to build a `Map` of all patterns that apply to the same base directory and set up a single watch per base. This allowed the API to remain unchanged but support larger trees, so long as your patterns are more specific.

**Comment by jfischoff** [comment]
@3noch Crap how did I just see this :p 

> I hope the fact that my tool is called twitch-cli does not bother you since I'm no longer actually using twitch. However, the CLI UI is still inspired by your library, so maybe that's enough?

More than enough!

> One thing I learned is that for very deep and large folders, it's not enough to have only one root directory. Having one root means that fsnotify must watch the entire tree which ends up being way too slow. What I did was use Glob's commonDirectory function to build a Map of all patterns that apply to the same base directory and set up a single watch per base. This allowed the API to remain unchanged but support larger trees, so long as your patterns are more specific.

Totally. Optimizing what is watch was a hope I had for `twitch` I just never had a reason and no one asked.
