### ISSUE TITLE
Get rid of getLine and rely on Ctrl+C

### ISSUE THREAD

**Issue by 3noch** [jfischoff/twitch#19]
Right now `defaultMain` relies on `getLine` [here](https://github.com/jfischoff/twitch/blob/master/src/Twitch/Main.hs#L267) to know when the program should stop. However, this makes it impossible to run the program in the background. You have to resort to antics like `coproc` and even that is hard to get working in a script. I think relying on `Ctrl-C` would be simpler and more robust.

**Comment by jfischoff** [comment]
Good point. I'll do that.
